codecov:
  max_report_age: off

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: 'header, reach, diff, flags, components'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

component_management:
  individual_components:
    - component_id: react-query
      name: '@tanstack/react-query'
      paths:
        - packages/react-query/**